### ISSUE TITLE
這個專案有hackpad嗎

### ISSUE THREAD

**Issue by yaodehaung** [g0v/blood#3]
可以提供一下嗎  謝謝

**Comment by taichunmin** [comment]
好像只有找到這個 http://blog.g0v.tw/posts/283244/blood-donation-centers-data-distribution

**Comment by yurenju** [comment]
@yaodehaung 雖然已經很久了還是回一下 XD
應該沒有，我當初因為 https://g0v.github.io/color/
有血液資訊的需要我就快速寫了這個爬蟲
因為那時候時間很趕所以也沒有什麼 hackpad，會動了就一直放著

**Comment by yurenju** [comment]
關了
