### ISSUE TITLE
API looks not working for 10 days?

### ISSUE THREAD

**Issue by tom76kimo** [g0v/blood#6]
API looks not working for 10 days?

**Comment by yurenju** [comment]
@tom76kimo thank you for reporting this issue, I will take a look tomorrow 👍

**Comment by yurenju** [comment]
seems github change the way to use personal access token, too bad :(

since it is needed to enter username and password, I may upload a ssh key to lambda or use other service like travis with crontab feature.

**Comment by yurenju** [comment]
@tom76kimo: fixed on commit 7a78601db4bf3ddab1bf51286f3ff8405764b93e, sadly we need to use travis-ci instead of aws lambda. thank you!
